# Generated by Django 4.1 on 2022-08-30 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormCadastro',
            new_name='Cadastro',
        ),
        migrations.RenameModel(
            old_name='FormCaracteristicas',
            new_name='Caracteristicas',
        ),
    ]
