# Generated by Django 4.1 on 2022-08-31 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_rename_formcadastro_cadastro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormCadPetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('apelido', models.CharField(max_length=30)),
                ('aniversario', models.DateTimeField(blank=True, null=True)),
                ('idade', models.IntegerField(default=0)),
                ('peso', models.IntegerField(default=0)),
                ('tamanho', models.IntegerField(default=0)),
                ('especie', models.CharField(choices=[('cachorro', 'CACHORRO'), ('gato', 'GATO'), ('coelho', 'COELHO'), ('cavalo', 'CAVALO'), ('peixe', 'PEIXE')], max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='caracteristicas',
            name='idnumber',
        ),
        migrations.DeleteModel(
            name='Cadastro',
        ),
        migrations.DeleteModel(
            name='Caracteristicas',
        ),
    ]
