# Generated by Django 4.1 on 2022-08-31 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0005_formcadpetmodel_racacachorro'),
    ]

    operations = [
        migrations.AddField(
            model_name='formcadpetmodel',
            name='caracteristicas',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='formcadpetmodel',
            name='coloracao',
            field=models.CharField(choices=[('amarelo', 'Amarelo'), ('branco', 'Branco'), ('caramelo', 'Caramelo'), ('marrom', 'Marrom'), ('preto', 'Preto')], default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='formcadpetmodel',
            name='pelagem',
            field=models.CharField(choices=[('1', 'Levemente Aspera'), ('2', 'Fios Lisos e Longos')], default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='formcadpetmodel',
            name='idade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='formcadpetmodel',
            name='tamanho',
            field=models.IntegerField(default=0),
        ),
    ]
