# Generated by Django 4.1 on 2022-08-31 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0008_rename_formcadpetmodel_formpet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formpet',
            name='especie',
            field=models.CharField(choices=[('cachorro', 'Cachorro'), ('gato', 'Gato'), ('coelho', 'Coelho'), ('cavalo', 'Cavalo'), ('peixe', 'Peixe')], max_length=10),
        ),
    ]
