# Generated by Django 4.1 on 2022-09-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0011_alter_formpet_aniversario_alter_formpet_apelido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formpet',
            name='aniversario',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Aniversário'),
        ),
    ]
